// <auto-generated />
using System;
using HW28_ASPNET_CORE_POSTMAN.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HW28_ASPNET_CORE_POSTMAN.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200530144825_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("HW28_ASPNET_CORE_POSTMAN.Models.Citata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Citatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Hurshed",
                            Date = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Grohnim vse"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Firdavs",
                            Date = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Dobudet svet"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Payrav",
                            Date = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "FREE Internet Unlim Forever"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Shahzod",
                            Date = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Kali luchshe tochno"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Karim",
                            Date = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Davay vrubimsya v CS1.6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
